name: Pipeline examen
on:
  push:
  workflow_dispatch: #manualmente
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Clonando el repositorio y estableciendo el espacio de trabajo
        uses: actions/checkout@v3
      - name: Configurando java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Ejecutando los test
        run: |
          chmod +x gradlew        
          ./gradlew test
      - run: echo "${{ github.actor }}"
  Publish:
    runs-on: ubuntu-latest
    needs: Test
    env:
      GITHUB_LOGIN: ${{ github.actor }}
      GITHUB_PACKAGES: ${{ secrets.TOKEN }}
      GITHUB_OAUTH: ${{ secrets.TOKEN }}
    steps:
      - name: Clonando el repositorio y estableciendo el espacio de trabajo
        uses: actions/checkout@v3
      - name: Configurando java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Publicando el artefacto
        run: |
          chmod +x gradlew        
          ./gradlew publish
      - run: echo '${{ github.actor }}'
  Mail:
    runs-on: ubuntu-latest
    needs: Publish
    steps:
      - name: Enviar correo
        uses: dawidd6/action-send-mail@v3.12.0
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL }}
          password: ${{ secrets.PASSWORD }}
          subject: "Ejecucion correcta."
          body: "Se ha ejecutado correctamente."
          to: ${{ secrets.DESTINATARIO }}
          from: ${{ github.actor }}
  Pantalla:
    runs-on: ubuntu-latest
    needs: Mail
    steps:
      - name: Mostrar mensaje por pantalla
        run: echo 'Pipeline ejecutado correctamente tras las acciones realizadas por el usuario ${{ github.actor }}'